data_engineering_project:
  outputs:
    dev:
      catalog: "{{ env_var('DATABRICKS_CATALOG', 'walmart') }}"
      host: "{{ env_var('DATABRICKS_HOST') | replace('https://', '') | replace('/', '') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      schema: "{{ env_var('DATABRICKS_SCHEMA', 'dbt_schema') }}"
      threads: 1
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      type: databricks
  target: dev
